### ISSUE TITLE
Add borrowing and returning functionality to Library class

### ISSUE THREAD

**Issue by UsmanAamir01** [UsmanAamir01/22F3709_22F3688#3]
We need to enhance the Library class by adding methods for borrowing and returning books.

- A method to borrow a book (borrowBook(String bookName)), which checks if the book is available and removes it from the list if borrowed.
- A method to return a book (returnBook(String bookName)), which adds the book back to the library's book list.
- Modify the listBooks method to show which books are currently borrowed.

**Comment by M-Sarim** [comment]
The code has been updated and the issue has been resolved.
